### ISSUE TITLE
After initial install, blocker will not activate on tabs that should be blocked for the first game

### ISSUE THREAD

**Issue by chiubaka** [Royl0406/Study-Duel#39]
It does seem to work for every game after that, though!

This is true for both the default block list and custom block lists.

**Comment by Royl0406** [comment]
In urlChangeHandler in background.js, the value of remainingBreakTimeMs is NaN on the first session. As a result, the blocker doesn't show up (ln 49).

**Comment by Royl0406** [comment]
breakStartTime was undefined on the first session. As a result, remainingBreakTime is NaN so screenBlocker wouldn't show even if the URL is distracting. Fixed with [this](https://stackoverflow.com/questions/1984721/how-to-handle-undefined-in-javascript)
